# Numpy Basic

In [2]:
import numpy as np

## data type

array의 dtype을 본다. 

In [72]:
arr = np.array([[1.,2,3,],[1,2,3]])

In [73]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [74]:
arr = arr.astype(np.int32) #float형을 int형으로 바꿔준다.
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [75]:
arr = np.array([[1., 2, 3], [1, 2, 3]], dtype=np.uint8)
# 바로 자료형을 지정해줄 수 있다.
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [76]:
len(arr.shape)

2

In [77]:
arr.shape

(2, 3)

size 확인

In [78]:
arr.size

6

dtype 확인

In [79]:
arr.dtype

dtype('uint8')

## Reshape

In [84]:
arr.shape

(1, 6)

Reshape 

In [85]:
arr = arr.reshape([1, 6]) #사이즈는 유지하되, shape를 바꿔준다.
arr.shape

(1, 6)

In [86]:
arr = np.array([[1,2,3],[1,2,3]])

In [87]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [89]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [91]:
arr = arr.reshape(-1,3)
arr.shape

# -1은 6의 size에서 3으로 나눌때 그에 해당 하는 값을 자동으로 매핑시켜준다.

(2, 3)

random array 생성

In [93]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [94]:
arr = arr.reshape([32,2])
arr.shape

(32, 2)

3차원으로 늘리기

In [97]:
arr = arr.reshape(-1,2,1,1,1,1)
arr.shape

(32, 2, 1, 1, 1, 1)

In [96]:
arr

array([[[-1.64652602e+00],
        [ 1.51942641e-01]],

       [[-8.64557974e-01],
        [ 1.67505109e+00]],

       [[ 3.14972839e-01],
        [ 1.22982984e-01]],

       [[ 9.81349236e-01],
        [-2.39047506e+00]],

       [[-1.51991574e-01],
        [ 1.97380380e+00]],

       [[ 6.05569267e-01],
        [-1.26692081e+00]],

       [[ 9.72124423e-01],
        [-2.85443991e-01]],

       [[ 1.24662216e+00],
        [-8.05829813e-01]],

       [[ 6.84065048e-01],
        [-6.23596850e-02]],

       [[-9.45333478e-01],
        [-5.17823818e-02]],

       [[-1.13778158e+00],
        [ 1.47556209e-01]],

       [[ 3.57089611e-01],
        [ 2.62788184e-01]],

       [[-1.32718239e+00],
        [ 1.40082694e-01]],

       [[-2.17872743e-01],
        [ 1.74315011e+00]],

       [[-3.06340042e-03],
        [-8.86182210e-01]],

       [[-5.08657692e-01],
        [ 2.00654174e+00]],

       [[ 9.14084780e-01],
        [ 1.02500653e+00]],

       [[ 4.34329476e-01],
        [ 4.89267146e

## Ravel

In [98]:
arr.shape

(32, 2, 1, 1, 1, 1)

In [99]:
arr=arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [102]:
arr.ravel() ==  arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [103]:
arr.shape

(64,)

In [104]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 64)

In [105]:
arr = arr.ravel()

In [106]:
arr.shape

(64,)

In [107]:
arr = np.expand_dims(np.expand_dims(arr, -1),0)

In [108]:
arr.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [3]:
zeros = np.zeros([3,3])
zeros
# 0으로 채워진 행렬이 만들어진다.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
zeros = np.zeros(1)
zeros

array([0.])

In [5]:
ones = np.ones([10])
ones
# size가 10인 ones가 생성된다.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
ones*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [11]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [12]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [13]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [15]:
nums = [1,2,3,4,5]

In [17]:
nums[2:]

[3, 4, 5]

In [19]:
arr[1]

# arr중 2번쨰 열

array([3, 4, 5])

In [20]:
nums = [1,2,3,4,[1,2,3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [21]:
nums[4]

[1, 2, 3]

In [22]:
arr[1][2]

5

# Slicing

In [23]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [24]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
arr[1:,1:]

# 1열 1행에서 시작해 나머지 데이터 불러오기

array([[4, 5],
       [7, 8]])

## Boolean Indexing

In [26]:
data = np.random.randn(3, 3)
data

array([[-0.31777355, -0.4792171 ,  0.94079675],
       [ 0.37767514, -1.06328867, -0.85924826],
       [ 0.29775827, -0.50898461,  0.62821019]])

In [28]:
data <= 0

# boolean형으로 결과를 반환할 수 있다.

array([[ True,  True, False],
       [False,  True,  True],
       [False,  True, False]])

In [31]:
data[data<=0] =1
# true인 부분만 define해준다.


data

array([[1.        , 1.        , 0.94079675],
       [0.37767514, 1.        , 1.        ],
       [0.29775827, 1.        , 0.62821019]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [32]:
import numpy as np

In [33]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr + 3
# 전체에 3씩 더해준다

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
arr * 3
# 전체에 3씩 곱해준다.

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [36]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [39]:
arr + 10
# 10을 다 더해주기

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [41]:
arr * 5
# 5를 다 곱해주기

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [42]:
arr + arr
# arr끼리 더해주기

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [46]:
np.add(arr, 1)
# 전체에 1씩 더해주기

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [50]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)


array([[[1, 0, 1],
        [0, 1, 1],
        [0, 1, 1]],

       [[1, 0, 0],
        [1, 1, 0],
        [0, 0, 1]],

       [[0, 0, 1],
        [0, 1, 1],
        [0, 0, 0]]])

In [51]:
arr

array([[[1, 0, 1],
        [0, 1, 1],
        [0, 1, 1]],

       [[1, 0, 0],
        [1, 1, 0],
        [0, 0, 1]],

       [[0, 0, 1],
        [0, 1, 1],
        [0, 0, 0]]])

In [52]:
arr_2

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 1]])

In [53]:
arr + arr_2

array([[[1, 1, 1],
        [0, 1, 2],
        [1, 1, 2]],

       [[1, 1, 0],
        [1, 1, 1],
        [1, 0, 2]],

       [[0, 1, 1],
        [0, 1, 2],
        [1, 0, 1]]])

In [54]:
arr * arr_2

array([[[0, 0, 0],
        [0, 0, 1],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]]])

In [55]:
np.sum(arr)

13

In [57]:
np.sum(arr + arr_2)
# 연산결과를 모두 더해준것

25

In [58]:
np.max(arr + arr_2)

2

In [59]:
np.min(arr + arr_2)

0

In [61]:
arr + arr_2

array([[[1, 1, 1],
        [0, 1, 2],
        [1, 1, 2]],

       [[1, 1, 0],
        [1, 1, 1],
        [1, 0, 2]],

       [[0, 1, 1],
        [0, 1, 2],
        [1, 0, 1]]])

In [62]:
np.sum(arr + arr_2, axis=-1) 
# -1차원의 합 여기서는 첫번쨰의 각 열의 합으로 새로운 열을 만듬!
# 1+1+1 = 3   0+1+2=3  1+1+2=4

array([[3, 3, 4],
       [2, 3, 3],
       [2, 3, 2]])

In [63]:
np.mean(arr)

0.48148148148148145

In [64]:
arr = np.array([1,6,3,7,3,2,9])
arr

array([1, 6, 3, 7, 3, 2, 9])

In [65]:
np.argmax(arr)
# 6번쨰 있는 값이 가장 크다.

6

In [66]:
np.argmin(arr)

0

In [67]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [69]:
np.unique(arr)
# 중복을 제거하여 반환

array([1, 3, 5, 6])

In [109]:
arr1 = [[1,2,3],[4,5,6]]

In [110]:
arr1

[[1, 2, 3], [4, 5, 6]]

In [112]:
test1 = np.array(arr1)


In [113]:
test1

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
arr11 = np.random.randint(2, size=36).reshape(3, 3, 4)
arr12 = np.random.randint(2, size=24).reshape(2, 3, 4)

In [116]:
arr11

array([[[0, 0, 0, 0],
        [1, 0, 1, 1],
        [0, 0, 1, 0]],

       [[0, 0, 1, 0],
        [0, 1, 0, 1],
        [0, 1, 0, 1]],

       [[1, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 0, 0]]])

In [117]:
arr12

array([[[0, 1, 1, 1],
        [1, 0, 1, 0],
        [1, 1, 1, 1]],

       [[1, 1, 0, 1],
        [0, 1, 0, 1],
        [1, 1, 0, 1]]])